# https://docs.docker.com/compose/environment-variables/

services:
  mattermost:
    container_name: mattermost
    cpus: "1.0"
    mem_reservation: 1g  # soft reservation
    mem_limit: 2g       # hard ceiling1~    mem_reservation: 32m  # soft reservation
    image: mattermost/${MATTERMOST_IMAGE}:${MATTERMOST_IMAGE_TAG}
    restart: ${RESTART_POLICY}
    security_opt:
      - no-new-privileges:true
    pids_limit: 200
    read_only: ${MATTERMOST_CONTAINER_READONLY}
    tmpfs:
      - /tmp
    volumes:
      - ${MATTERMOST_CONFIG_PATH}:/mattermost/config:rw
      - ${MATTERMOST_DATA_PATH}:/mattermost/data:rw
      - ${MATTERMOST_LOGS_PATH}:/mattermost/logs:rw
      - ${MATTERMOST_PLUGINS_PATH}:/mattermost/plugins:rw
      - ${MATTERMOST_CLIENT_PLUGINS_PATH}:/mattermost/client/plugins:rw
      - ${MATTERMOST_BLEVE_INDEXES_PATH}:/mattermost/bleve-indexes:rw
    environment:
      # timezone inside container
      - TZ

      # necessary Mattermost options/variables (see env.example)
      - MM_SQLSETTINGS_DRIVERNAME
      - MM_SQLSETTINGS_DATASOURCE

      # necessary for bleve
      - MM_BLEVESETTINGS_INDEXDIR

      # additional settings
      - MM_SERVICESETTINGS_SITEURL
      - APP_PORT
    networks:
      - mattermost-net
      - docker_db_scripts
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4080/api/v4/system/ping"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: mattermost_cldflr
    # ── resource caps ────────────────────────────
    cpus: "0.25"          # max 25 % of one logical core
    mem_reservation: 32m  # soft reservation
    mem_limit: 128m       # hard ceiling
    # ─────────────────────────────────────────────
    restart: ${RESTART_POLICY}
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    environment:
      - TUNNEL_TOKEN
    networks:
      - mattermost-net

networks:
  mattermost-net:
    external: true

  docker_db_scripts:
    external: true
